### ISSUE TITLE
USATV Go

### ISSUE THREAD

**Issue by HenioH** [Tempest0580/Temptv#18] opened 2019-12-07 16:37 UTC
Stop working a couple days ago any word on a fix? was so reliable till then.

**Comment by Tempest0580** [comment] 2019-12-07 17:47
Are you up to date? I am currently watching channels from Usatv Go

**Comment by HenioH** [comment] 2019-12-07 17:57
Thank you for the reply. It shows Version 2.0.35 for TEMPTV. For the last 48 hours or so when I click on a channel in USAtv go nothing plays. I tried clearing cache and also tried it on a few different devices and none of the channels play. No error at all it just acts like its going to open the channel then nothing

**Comment by jewbmx** [comment] 2019-12-07 18:07
Works fine for me. Just tried amc without any issues

**Comment by HenioH** [comment] 2019-12-07 18:17
Weird I just tried it on a fresh empty Kodi install with only the temptv repo install then temptv addon and nothing will play from the usago tv. Spins then nothing. Acronai plays but nothing in usatv go.

**Comment by HenioH** [comment] 2019-12-08 19:01
Im running 17.6 and in the states. Ive tried a fresh install on a blank kodi, no IP address, VPN and still cant get a a channel in usatv go. is there something im missing? It was working perfect a couple days ago

**Comment by Tempest0580** [comment] 2019-12-08 19:07
I highly recommend to start by updating kodi to 18.5 then test it again. And let me know. I'm not seeing and issues getting them to play.

**Comment by HenioH** [comment] 2019-12-08 19:50
That's exactly what it was. Won't function on 17.6 anymore. Works on 18.5.. I was dreading having to re do my entire build for 18.5 lol. Would it be something simple to get it to work on 17.6 again?

**Comment by jewbmx** [comment] 2019-12-08 20:00
I didnt change anything that should effect the kodi version diference but either way i say get with the times or learn to code yourself lol. (I personally only pay attention to supporting the version i use.)

**Comment by jewbmx** [comment] 2019-12-08 20:17
Looked it over again and the only thing i can think of is that maybe 17.6 doesnt like the little header code added to the play link. Removing it breaks it tho so you'd be screwed.

**Comment by Tempest0580** [comment] 2019-12-08 20:43
I think Jewbmx is correct.  I took a quick look and it seems updating to 18.5 would be your only option.

**Comment by HenioH** [comment] 2019-12-08 21:06
I was looking at it also couldn't find anything different from the previous version. Its probably time I take the leap to the newer Kodi. Thank you both for your input really appreciate it. Atleast if anyone else mentions the issue could just be the Kodi version they are on.

**Comment by JayDee696969** [comment] 2019-12-09 03:38
Not working as of today for me either, latest version, and Kodi 18.5.In east coast US.`2019-12-08 22:36:51.949 T:15132   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.temptv/?action=ustvgoPlay&url=http%3A%2F%2Fustvgo.tv%2Fcnbc-live-streaming-free
2019-12-08 22:36:51.962 T:14988   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.temptv/?action=ustvgoPlay&url=http%3A%2F%2Fustvgo.tv%2Fcnbc-live-streaming-free) failed
2019-12-08 22:36:59.202 T:13736   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.temptv/?action=ustvgoPlay&url=http%3A%2F%2Fustvgo.tv%2Fdestination-america
2019-12-08 22:36:59.203 T:14988   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.temptv/?action=ustvgoPlay&url=http%3A%2F%2Fustvgo.tv%2Fdestination-america) failed`

**Comment by JayDee696969** [comment] 2019-12-09 03:45
[kodi.log](https://github.com/Tempest0580/Temptv/files/3937795/kodi.log)

**Comment by vortex91** [comment] 2019-12-09 05:58
looks like somethign changed as of 2 hours ago

**Comment by vortex91** [comment] 2019-12-09 06:20
https://peer2.ustv.to/Animal/myStream/chunks.m3u8?nimblesessionid=95112513&wmsAuthSign= 
looks like seesionid added

**Comment by jewbmx** [comment] 2019-12-09 09:01
Yall make me giggle sometimes lol.

https://textuploader.com/1oudx/raw

This time lets try to keep the chatter on places like reddit to a minimum since thats a global snitchboard.

**Comment by Tempest0580** [comment] 2019-12-09 10:17
I'll push a update this afternoon.  Thanks again Jewbmx.

**Comment by bjgood** [comment] 2019-12-09 20:34
JewBMX's fix needs this change...

change this...
self.base_link = 'http://ustvgo.tv'

to this...
self.base_link = 'http://ustvgo.tv/'

then it works...at least for me.

**Comment by Tempest0580** [comment] 2019-12-09 20:44
Ok I'll check it out after work. Thanks

**Comment by YKL66** [comment] 2019-12-09 20:51
The (v2.0.35) broke my (ustvgo) on my (M8 box) running (LibreELEC 8.2.5.1) (Kodi 17.6). My Win10, and (3) T95m boxes) are okay off and on with the (2.0.35). So I just went back to ( TempTV zip version 2.0.32) and all is perfect again. Hope this helps as a temporary fix for now. Thanks for all the hard work.

**Comment by YKL66** [comment] 2019-12-09 21:15
The (v2.0.35) broke my (ustvgo) on my (M8 box) running (LibreELEC 8.2.5.1) (Kodi 17.6). My Win10, and my (3) T95m boxes) running kodi 18.5 are okay off and on with the (2.0.35). So I just went back to (TempTV zip version 2.0.32) and all is perfect again for now. Hope this helps as a temporary fix for now. Thanks for all the hard work.

PS: 2.0.32 has now stop working today. After writing a earlier post for my LE 17.6. again thanks for all the hard work.

**Comment by jewbmx** [comment] 2019-12-09 21:32
The / is moved to each individual item in the most recent update because when the iframe result is returned it has one already lol. It was tested before shared and works properly if the entire scripts replaced like it should be lol.

As for your kodi 17.6 problem thats because your on old unsupported shit lol we found that out the other day. Gotta fiddle with the final url that adds the header in order to use it on 17.6

**Comment by bjgood** [comment] 2019-12-09 21:56
You know your stuff, JewBMX, and I'm sure you're right. I'm just reporting what I had to do to get it working (after checking the Kodi log first for any information, of course).

2019-12-09 15:17:37.588 T:1799328640   ERROR: GetDirectory - Error getting plugin://plugin.video.tempest/?action=ustvgoPlay&url=http%3a%2f%2fustvgo.tvmsnbc-live-streaming-free
2019-12-09 15:17:37.590 T:1936955840   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tempest/?action=ustvgoPlay&url=http%3a%2f%2fustvgo.tvmsnbc-live-streaming-free) failed

**Comment by bjgood** [comment] 2019-12-09 22:58
I should add that I transferred JewBMX's code over to Tempest's file, excluding the channel list. In Tempest's channel list he excludes the forward slash in front of the channel address (example...msnbc-live-streaming-free). JewBMX has the forward slash included in his channel list address. So, JewBMX is correct in his code.

It's just an example of two different approaches to a situation.

The error was mine for not explaining in more depth the steps I took when constructing my ustvgo.py file.

Sorry for the confusion.

**Comment by vortex91** [comment] 2019-12-10 00:57
yoru missing the point.  Upgrade to new builds as most devs will not bother supporting older builds and in this case they dont want your to report bugs on old builds also.

**Comment by jewbmx** [comment] 2019-12-10 01:07
All versions of this script used between me and tempest are the same when it comes to the coding lol. Only difference is version and the changes made for that version. Only thing we really ever did differently was artwork and maybe the titles.  Id suggest using winmerge to compare the files if you wanna swap bits instead of the whole thing.

Oh and the process you took from the git go was realized lol, its the only way it could error for ya ;)

**Comment by schwifty42069** [comment] 2019-12-10 02:07
I have a similar script that's also broke. If I can find an efficient way around the WAF, I'll share!

**Comment by vortex91** [comment] 2019-12-10 02:34
i gave u the fix in the ticket  on yoru git line 56

**Comment by schwifty42069** [comment] 2019-12-10 02:49
@vortex91 that's not the issue. The issue is that the js the script pulls the links from is hidden on the page now and that's IF you don't get stuck by the waf, which I am, constantly. My script never pulled the token from the chunklist, it's always pulled it from the playlist.

**Comment by YKL66** [comment] 2019-12-10 03:13
Temptv Version 2.0.36 Has All my boxes working ustvgo again. You kats are really good at this.

**Comment by schwifty42069** [comment] 2019-12-10 03:49
@vortex91 Thank you, I just realized using the direct iframe link with a firefox user-agent header completely bypasses the WAF. No more selenium required! Woohooo!

**Comment by HenioH** [comment] 2019-12-10 07:37
The new update works on 17.6 & 18.5!! great fix. Thanx

**Comment by jabales** [comment] 2019-12-11 06:30
Any one else loose the feed to HBO and Showtime?

**Comment by Tempest0580** [comment] 2019-12-24 18:18
Pushed a Update to Fix HBO and Showtime streams.

**Closed** 2019-12-31 12:30 UTC

**Comment by jabales** [comment] 2020-01-06 23:26
Thanks, Tempest!
